staging:
  adapter: mysql2_makara
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  database: <%= ENV.fetch("DATABASE_NAME") %>
  host: <%= ENV.fetch("DATABASE_HOST") %>
  port: <%= ENV.fetch("DATABASE_PORT") %>
  reconnect: true
  socket: <%= [
  '/var/run/mysqld/mysqld.sock',
  '/var/lib/mysql/mysql.sock',
  '/tmp/mysqld.sock',
  '/tmp/mysql.sock'].detect { |socket| File.exist?(socket) } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD", "") %>
  variables:
    sql_mode: 'NO_ENGINE_SUBSTITUTION'

  makara:
    id: mysql
    connections:
      - role: master
        host: <%= ENV.fetch("DATABASE_HOST") %>
        name: Master
      <% if ENV["USE_DB_WORKER_REPLICAS"] == "true" %>
      - role: slave
        host: <%= ENV.fetch("DATABASE_HOST") %>
        name: Worker Replica 1
      <% end %>
